### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by insomniacslk**
Based on @natolumin's initial work at https://github.com/Natolumin/coredhcp/commit/c37fbceece39be191719225e856f65ae8f4b31e1

Signed-off-by: Andrea Barberio <insomniac@slackware.it>

### CODE REVIEW

**Comment by insomniacslk** [comment]
This PR adds an integration test for a basic DHCPv6 IA_NA transaction

**Comment by Natolumin** [comment]
I think coverage doesn't really work yet: 
```
==> GitHub Actions detected.
->  Issue detecting commit SHA. Please run actions/checkout with fetch-depth > 1 or set to 0
    project root: .
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    - file not found at coverage.txt
--> No coverage data found.
```

So I think we need to 
 * add fetch-depth: 0 to the checkout step (I think that checks out the whole history but that's often cheaper than computing a sparse checkout for git)
 * pass the full `$GITHUB_WORKSPACE/src/github.com/${{ github.repository }}/integ/coverage.txt` path in the codecov step

**Review by Natolumin — DISMISSED** [review]
otherwise looks fine, let's go with this and build on it

**Comment by insomniacslk** [comment]
>     * add `fetch-depth: 0` to the checkout step (I think that checks out the whole history but that's often cheaper than computing a sparse checkout for git)
> 
>     * pass the full `$GITHUB_WORKSPACE/src/github.com/${{ github.repository }}/integ/coverage.txt` path in the codecov step

Done, and also configured CodeCov for coredhcp since it wasn't (and I thought it was)

**Comment by insomniacslk** [comment]
configured using the github action instead, and forcing a CI failure if codecov upload fails

**Comment by insomniacslk** [comment]
this should be ready to merge now, needs approval again

**Comment by insomniacslk** [comment]
actually I can use superpowers since it was already approved

**Pull request merged**
